---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guestbook-db
  namespace: guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DB_PASSWORD: AgCk1SRyXV1H58upHt2vvE3MOL/2cWSvQ+MDNDEdpdlzb8ZHKAWsSkNNM/O36yjsQy6Wd/1l7qUMu9am5BgsFo0qru41bEQlhDEAGdkAxupkHlHEyc3jqHqJiMYivzs5Ai3s91y+qp4oOryPsXjbjsFSQ88czowYy3g7j5GcIs+wnwgPgZ5VcJ63Sk+7HoSoqzIJMpUF2lo4BSc/PmadyIgV5vqSTbUTAF83wQRxVaf+pdnd/blMA8IDBTFFNeHo3KnWN3vNFHiWCytq/c55Scltlpf7hL70+Rwag1+gEbr+T9rKaAmDo2Owx4W1YCO40j4sjdIPUijM/zlniyau9vxAPSlq+zim4O/A/NKWT+2eGWNqJYspFvzA2B4AATBq8ciUvyBngS4sMoB2bkZgyy511VnuraL33UqO9R8SteJT3sutfcuIvuAZIszUmOBDDH0XL9TyLkAApgvE6ksRwbjq9vhpdOZ+mlRs/4tghB+WnTOy1E3shT8ZKHnQZa/ESORE4VGIMUzRwCvDefU5GibJ0KIbDWMXABpXr72ge9merh9h9tTICPNL55UHZLrJqp8Y/6CYdQhDSI4AJN7sj8mqn1BRqhq5R1yLEmP8TjunCpOQ8BsgFC2JKGSMe5eU4m7yD4GQ6FKP+X/j8a2KqpZ1sk+F4ZQDnoScUe7pZeSLYvhL63jWWDdVEoib6JnCFS+rhE3Iyez9Q47CjA==
  template:
    metadata:
      name: guestbook-db
      namespace: guestbook
